# Generated by Django 5.0.3 on 2024-03-15 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('track_type', models.CharField(choices=[('Metropolitan', 'Metropolitan'), ('Country', 'Country'), ('Other', 'Other')], default='Other', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('odds', models.FloatField(help_text='Decreasing odds show more people betting on this horse')),
                ('current_form', models.CharField(max_length=255)),
                ('barrier', models.IntegerField()),
                ('track_conditions', models.CharField(max_length=255)),
                ('race_location', models.CharField(max_length=255)),
                ('jockey', models.CharField(max_length=255)),
                ('trainer', models.CharField(max_length=255)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horses', to='betfair_bot.market')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(max_length=255)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=6)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('won', models.BooleanField(default=False)),
                ('payout', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='betfair_bot.market')),
            ],
            options={
                'ordering': ['-market__start_time'],
            },
        ),
    ]
