# Generated by Django 5.0.3 on 2024-03-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetfairData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('track', models.CharField(max_length=100)),
                ('race_number', models.IntegerField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('age_restrictions', models.CharField(max_length=50)),
                ('class_restrictions', models.CharField(max_length=50)),
                ('weight_restrictions', models.IntegerField()),
                ('race_prizemoney', models.TextField()),
                ('horse_name', models.CharField(max_length=100)),
                ('horse_age', models.IntegerField()),
                ('horse_sex', models.CharField(max_length=10)),
                ('horse_number', models.IntegerField(blank=True, null=True)),
                ('horse_jockey', models.CharField(max_length=100)),
                ('horse_barrier', models.IntegerField(blank=True, null=True)),
                ('horse_trainer', models.CharField(max_length=100)),
                ('horse_weight', models.FloatField(blank=True, null=True)),
                ('horse_claim', models.FloatField(blank=True, null=True)),
                ('horse_last10', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record_distance', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record_track', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record_track_distance', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record_fast', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record_good', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record_dead', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record_slow', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record_heavy', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record_jumps', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record_first_up', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_record_second_up', models.CharField(blank=True, max_length=100, null=True)),
                ('horse_prize_money', models.FloatField(blank=True, null=True)),
                ('form_barrier', models.IntegerField(blank=True, null=True)),
                ('form_class', models.CharField(blank=True, max_length=100, null=True)),
                ('form_distance', models.IntegerField(blank=True, null=True)),
                ('form_jockey', models.CharField(blank=True, max_length=100, null=True)),
                ('form_margin', models.FloatField(blank=True, null=True)),
                ('form_meeting_date', models.DateField(blank=True, null=True)),
                ('form_name', models.CharField(blank=True, max_length=100, null=True)),
                ('form_other_runners', models.CharField(blank=True, max_length=100, null=True)),
                ('form_position', models.IntegerField(blank=True, null=True)),
                ('form_price', models.FloatField(blank=True, null=True)),
                ('form_time', models.TimeField(blank=True, null=True)),
                ('form_track', models.CharField(blank=True, max_length=100, null=True)),
                ('form_track_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('form_weight', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
