# Generated by Django 5.0.3 on 2024-03-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betfair_bot', '0002_betfairdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='betfairdata',
            name='country_code',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
